= brandon-utils
:note-caption: 📰
:jetbrains-embedded: link:https://forum.unity.com/threads/embedded-jetbrains-annotations-in-v5-unityengine-dll.304819/#:~:text=This%20is%20intentional%2C%20yes%2C%20and%20you%20can%20rely%20on%20the%20attributes%20being%20included%20in%20all%20future%20versions%20of%20Unity.[embedded]

> Stuff link:https://brandoncimino.com[Brandon] wants in every Unity project.

.Regarding Namespaces
NOTE: For some reason, `Runtime` seems to be omitted.
I'm going to trust Rider on this one.

[NOTE]
====
This package uses `com.unity.nuget.newtonsoft-json` as a dependency (rather than https://github.com/jilleJr/Newtonsoft.Json-for-Unity[Newtonsoft.Json for Unity]) because https://docs.unity3d.com/Manual/upm-git.html[git dependencies are not supported for packages].

It may be possible to move to https://github.com/jilleJr/Newtonsoft.Json-for-Unity[Newtonsoft.Json for Unity] using the package's newer methods of dependency inclusion.
====

== To-Do's

- [ ] Improve link:Runtime/Logging/LogUtils.cs[] so that it can be referenced from _any_ assembly
** I don't think conditional compiling will work, because the `.asmdef` isn't conditional in that way...
** I might have to go _real_ hard, and use https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods[partial classes]!
** 🆕 _Oct 11, 2022_: I should use the link:https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger?view=dotnet-plat-ext-6.0[ILogger] interface and have consumers of BrandonUtils pass in an `ILogger` instancefootnote:[https://stackoverflow.com/questions/2764384/logging-in-a-c-sharp-library[Logging in a C# library]]
- [x] Fix usage of JetBrains attributes (e.g. `[UsedImplicitly]`)
** This requires a link:Dependency_Management.adoc[Nuget dependency] on the https://www.nuget.org/packages/JetBrains.Annotations/[JetBrains.Annotations] package.
** The package must be embedded inside of the link:NuGet/[] folder and included in source control.
** Must *only* be used by link:Standalone/[]footnote:[Unity has a copy of `JetBrains.Annotations` {jetbrains-embedded} inside of it, which is accessible from inside link:Runtime/[] and link:Editor/[].]
** The `.dll` files must be referenced *explicitly* by ``.asmdef``s
*** By default, all `.dll` assemblies are imported with "*Implicitly Referenced*" set to `true`
*** Doing this causes Unity to have a conniption, because it causes naming conflicts with the {jetbrains-embedded} version.

== Naming Convention

- Would it be useful to make a unified prefix for classes, or are namespaces enough?
For example, `BrandonUtils` is very similar to this person's https://forum.unity.com/threads/whats-in-your-standard-c-toolkit.1088626/#post-7012039[Spacepuppy Framework], where each class is prefixed with `SP`
